openapi: 3.0.1
info:
  title: Store and Stock Management API
  description: API for managing stores, stock, and admin users
  version: 1.0.0

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/uvadevopslab/tutorial/1.0.0
  - url: https://{env}.example.com/{version}
    variables:
      env:
        default: dev    
        enum:
          - prod         
          - dev     
          - testing
      version:
        default: v1

paths:
  /items:
    get:
      tags: 
        - Item Management  
      summary: Gets all stock item definitions
      operationId: getAllItemDefs
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ItemTemplate"
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
    put:
      tags: 
        - Item Management
      summary: Adds or updates item definition
      operationId: updateItemDef
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Added/Updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemTemplate"
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'

  /items/{itemId}:
    get:
      tags: 
        - Item Management
      summary: Gets target item definition
      operationId: getItemDef
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemTemplate"
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
    delete:
      tags: 
        - Item Management
      summary: Deletes target item definition
      operationId: deleteItemDef
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Deleted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemTemplate"
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'

  /stores:
    get:
      tags: 
        - Store Management
      summary: Gets all stores
      operationId: getAllStores
      responses:
        '200':
          description: List of available stores
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Store"
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
    put:
      tags: 
        - Store Management
      summary: Adds or updates a store
      operationId: updateStore
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Store updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Store"
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'

  /stores/{storeId}:
    get:
      tags: 
        - Store Management
      summary: Gets target store
      operationId: getStoreById
      parameters:
        - name: storeId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Store details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Store"
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
    delete:
      tags: 
        - Store Management
      summary: Deletes a store
      operationId: deletetore
      parameters:
        - name: storeId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Store removed
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'

  /stores/{storeId}/stock/:
    get:   
      tags:
        - Store Management
      summary: Gets all stock items from specified store
      operationId: getStoreInventory
      parameters:
        - name: storeId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/StoreItem"
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
    put:   
      tags:
        - Store Management
      summary: Adds or updates stock item from specified store
      operationId: updateStoreItem
      parameters:
        - name: storeId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/StoreItem"
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
                  
  /stores/{storeId}/stock/{stockId}:
    get:   
      tags:
        - Store Management
      summary: Gets stock item from specified store
      operationId: getStoreItem
      parameters:
        - name: storeId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: stockId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/StoreItem"
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
    post:
      tags: 
        - Store Management
      summary: Moves specified stock item to target store
      operationId: moveStockItem
      parameters:
        - name: storeId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: stockId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  format: int32
                toStore:
                  type: string
                  format: uuid
      responses:
        '200':
          $ref: "#/components/responses/SuccessResponse"
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
      x-amazon-apigateway-integration:
        type: AWS_PROXY
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        uri: "${move_stock_item_arn}"
    delete:   
      tags:
        - Store Management
      security:
        - bearerAuthAdmin: []
      summary: Deletes stock item from specified store
      operationId: deleteStoreItem
      parameters:
        - name: storeId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: stockId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/StoreItem"
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        

  /cart:
    get:   
      tags:
        - User Cart Management
      summary: Gets the logged-in user's shopping cart
      operationId: getUserCart
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/StoreItem"
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
    put:
      tags: 
        - User Cart Management
      summary: Adds or updates stock item to the logged-in user's shopping cart
      operationId: updateCartItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StoreItem"
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'

  /cart/stock/{stockId}:
    delete:
      tags: 
        - User Cart Management
      summary: Removes stock item from the logged-in user's shopping cart
      operationId: removeItemFromCart
      parameters:
        - name: stockId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StoreItem"
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'

  /cart/reserve/{stockId}:
    post:
      tags: 
        - User Cart Management
      summary: Reserves an out-of-stock stock item
      operationId: reserveStockItem
      parameters:
        - name: stockId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
      responses:
        '200':
          $ref: '#/components/responses/SuccessResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'

components:
  schemas:
    ItemTemplate:
      type: object
      required:
        - id
        - name
        - storedIn
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: Watch
    StoreItem:
      type: object
      required:
        - id
        - quantity
      properties:
        item:
          $ref: "#/components/schemas/ItemTemplate"
        quantity:
          type: integer
          format: int32
          example: 1102
    Store:
      required:
        - name
        - address
      properties:
        name:
          type: string
          example: ACME Corporation
        address:
          type: string
          format: address
          example: 'Via Roma'
      type: object
  securitySchemes:
    JWTAuth:
      type: https
      scheme: bearer
      bearerFormat: JWT
  responses:
    SuccessResponse:
      description: Success
    UnauthorizedResponse:
      description: You need to be authenticated to perform this action.
    ForbiddenResponse:
      description: You don't have the necessary permissions to perform this action.
    NotFoundResponse:
      description: Resource not found